name: energyfi
description: EnergyFi â€“ STO Investor Dashboard (Mobile)

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # State Management
  flutter_riverpod: ^2.6.1
  # Web3
  web3dart: ^2.7.3
  walletconnect_flutter_v2: ^2.4.4
  # Network
  http: ^1.3.0
  # Local Storage
  shared_preferences: ^2.5.3
  # Routing
  go_router: ^15.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
